import { useState } from 'react';
import { Check, CircleHelp, Layers, Leaf, Lightbulb, Palette, ShieldCheck, Sparkles, X } from 'lucide-react';
import type { ReactNode } from 'react';
import type { Version } from '../types/moodboard.types';
import { categories, roles, findingText, strengths } from '../types/moodboard.types';
import { sourceUrl } from '../api/moodboards-api';
import { Dialog, Notice, Pill } from './WorkspaceUi';

export function HumanSummaryView({version, projectId, boardId, onReview}: {version: Version; projectId:string; boardId:string; onReview: () => void}) {
  const summary = version.human_summary;
  const [selectedRef, setSelectedRef] = useState<string | null>(null);
  if (!summary) return null;
  const ref = summary.referensi.find(r => r.id === selectedRef);
  const source = ref && version.snapshot.sources.find(source => ref.id.startsWith(source.prefix + '-'));
  const refs = (ids: string[]) => <div className="mt-3 flex flex-wrap gap-1.5">{ids.map(id => <button key={id} onClick={() => setSelectedRef(id)} className="rounded border border-stone-200 bg-stone-50 px-1.5 py-0.5 font-mono text-[10px] text-stone-500 hover:border-forest-200 hover:text-forest-700">{id}</button>)}</div>;
  const section = (title: string, icon: ReactNode, children: ReactNode) => <section key={title} className="mb-panel p-6"><div className="mb-4 flex items-center gap-2.5 text-forest-600">{icon}<h2 className="text-sm font-semibold text-ink">{title}</h2></div>{children}</section>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Pill status={version.review_status}/><span className="rounded-md border border-stone-200 bg-white px-2 py-1 text-[11px] text-stone-500">{({cukup_jelas:'Visual cukup jelas',sebagian_jelas:'Visual sebagian jelas',kurang_jelas:'Visual kurang jelas'} as Record<string,string>)[summary.status_analisis]}</span></div><span className="text-xs text-stone-400">Hasil versi {version.version_number}</span></div>
    {version.review_status !== 'approved' && <Notice kind="info"><div className="flex flex-wrap items-center justify-between gap-3"><span>Ini interpretasi AI. Periksa temuan dan arahan sebelum digunakan.</span><button onClick={onReview} className="font-semibold underline">Review temuan</button></div></Notice>}
    <section className="relative overflow-hidden rounded-xl border border-forest-200 bg-[#edf4ee] p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-forest-600"><Sparkles size={15}/>Ringkasan visual</div><p className="mt-4 max-w-3xl whitespace-pre-line text-lg leading-8 text-forest-700">{summary.ringkasan_visual || 'Ringkasan tidak ditetapkan pada versi ini.'}</p>{refs(summary.referensi.map(r => r.id))}</section>
    <div className="grid gap-5 lg:grid-cols-2">
      {section('Gaya utama', <Leaf size={18}/>, <><p className="text-sm leading-6 text-stone-600">{summary.gaya_utama.deskripsi}</p><div className="mt-4 flex flex-wrap gap-2">{summary.gaya_utama.ciri_utama.map(value => <span key={value} className="rounded-md bg-stone-100 px-2.5 py-1.5 text-xs text-stone-600">{value}</span>)}</div><p className="mt-4 text-[11px] text-stone-400">{summary.gaya_utama.dasar.replaceAll('_',' ')} · Keyakinan {summary.gaya_utama.keyakinan}</p>{refs(summary.gaya_utama.referensi)}</>)}
      {section('Nuansa & suasana', <Sparkles size={18}/>, summary.nuansa.length ? <div className="space-y-4">{summary.nuansa.map((mood,i) => <div key={i} className={i ? 'border-t border-stone-100 pt-4' : ''}><p className="text-sm font-medium">{mood.nama}</p><p className="mt-1 text-xs leading-5 text-stone-500">{mood.penyebab_visual}</p><p className="mt-2 text-[11px] text-stone-400">{mood.dasar} · Keyakinan {mood.keyakinan}</p>{refs(mood.referensi)}</div>)}</div> : <p className="text-sm text-stone-400">Belum ada nuansa yang ditetapkan.</p>)}
    </div>
    {section('Palet warna', <Palette size={18}/>, <><p className="mb-5 text-xs text-stone-400">Kode warna merupakan perkiraan dari referensi visual.</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{summary.palet_warna.map((color,i) => <div key={i} className="overflow-hidden rounded-lg border border-stone-200"><div className="h-20 border-b border-stone-100" style={{backgroundColor: color.hex_perkiraan || '#eeeeea'}} aria-label={`Warna ${color.warna}`}/><div className="p-3"><p className="text-xs font-semibold">{color.warna}</p><p className="mt-1 font-mono text-[10px] text-stone-400">{color.hex_perkiraan || 'Tidak diketahui'}</p><p className="mt-2 text-[11px] leading-4 text-stone-500">{color.peran_visual}</p>{refs(color.referensi)}</div></div>)}</div>{!summary.palet_warna.length && <p className="text-sm text-stone-400">Belum ada warna yang ditetapkan.</p>}</>)}
    {section('Elemen visual', <Layers size={18}/>, <div className="grid gap-x-8 gap-y-5 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(summary.elemen_visual).map(([key, values]) => <div key={key}><h3 className="mb-2 text-xs font-semibold text-stone-700">{categories[key] || key}</h3>{values.length ? <ul className="space-y-2 text-xs leading-5 text-stone-500">{values.map((value,i) => <li key={i} className="flex gap-2"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-forest-500"/>{value}</li>)}</ul> : <p className="text-xs text-stone-400">Tidak ditentukan</p>}</div>)}</div>)}
    {summary.kelompok_visual.length > 0 && section('Kelompok visual', <Layers size={18}/>, <div className="space-y-4">{summary.kelompok_visual.map((group,i) => <div key={i}><p className="text-sm font-medium">{group.nama}</p><p className="mt-1 text-xs leading-5 text-stone-500">{group.deskripsi}</p>{refs(group.referensi)}</div>)}</div>)}
    <div className="grid gap-5 lg:grid-cols-2">{(['gunakan','hindari'] as const).map(kind => section(kind === 'gunakan' ? 'Yang digunakan' : 'Yang dihindari', kind === 'gunakan' ? <Check size={18}/> : <X size={18}/>, <div className="space-y-4">{summary.panduan_bersama[kind].map((guide,i) => <div key={i}><p className="text-sm font-medium">{guide.arahan}</p><p className="mt-1 text-xs leading-5 text-stone-500">{guide.alasan}</p>{refs(guide.referensi)}</div>)}{!summary.panduan_bersama[kind].length && <p className="text-xs text-stone-400">Belum ada panduan yang ditetapkan.</p>}</div>))}</div>
    {(version.instructions.length > 0 || version.findings.some(f => ['accepted','edited'].includes(f.review_state) && f.strength !== 'reference_only')) && section('Arahan yang dikonfirmasi manusia', <ShieldCheck size={18}/>, <ul className="space-y-3">{version.findings.filter(f => ['accepted','edited'].includes(f.review_state) && f.strength !== 'reference_only').map(f => <li key={f.id} className="text-sm leading-6 text-stone-600"><span className="mr-2 rounded bg-forest-50 px-2 py-1 text-[10px] text-forest-700">{strengths[f.strength]}</span>{findingText(f.reviewed_value)}</li>)}{version.instructions.map((item,i) => <li key={`instruction-${i}`} className="text-sm text-stone-600"><span className="mr-2 rounded bg-forest-50 px-2 py-1 text-[10px] text-forest-700">{strengths[item.strength]}</span>{item.text}</li>)}</ul>)}
    {summary.perbedaan_atau_konflik.length > 0 && section('Perbedaan & konflik', <CircleHelp size={18}/>, <div className="space-y-4">{summary.perbedaan_atau_konflik.map((conflict,i) => <div key={i}><p className="text-sm text-stone-600">{conflict.deskripsi}</p>{refs(conflict.referensi)}<p className="mt-2 text-xs text-forest-700">{version.conflict_resolutions[String(i)] || 'Belum ada keputusan manusia.'}</p></div>)}</div>)}
    <div className="grid gap-5 lg:grid-cols-2">{section('Pertanyaan klarifikasi', <CircleHelp size={18}/>, <ul className="space-y-3 text-xs leading-5 text-stone-500">{summary.pertanyaan_klarifikasi.map((text,i) => <li key={i}>{text}</li>)}{!summary.pertanyaan_klarifikasi.length && <li>Tidak ada pertanyaan terbuka.</li>}</ul>)}{section('Keterbatasan analisis', <Lightbulb size={18}/>, <ul className="space-y-3 text-xs leading-5 text-stone-500">{summary.keterbatasan.map((text,i) => <li key={i}>{text}</li>)}{!summary.keterbatasan.length && <li>Tidak ada keterbatasan yang dilaporkan.</li>}</ul>)}</div>
    {section('Referensi sumber', <Layers size={18}/>, <div className="grid gap-3 sm:grid-cols-2">{summary.referensi.map(ref => <button key={ref.id} className="rounded-lg border border-stone-100 p-4 text-left hover:border-forest-200" onClick={() => setSelectedRef(ref.id)}><span className="font-mono text-[10px] text-forest-600">{ref.id} · {ref.lokasi}</span><p className="mt-2 text-xs leading-5 text-stone-500">{ref.deskripsi_singkat}</p></button>)}</div>)}
    {ref && source && <Dialog title={`Referensi ${ref.id}`} wide onClose={() => setSelectedRef(null)}><img src={sourceUrl(projectId,boardId,source.id,false)} alt={ref.deskripsi_singkat} className="max-h-[55vh] w-full rounded-lg object-contain"/><div className="mt-4"><p className="text-sm font-medium">{ref.lokasi}</p><p className="mt-1 text-sm text-stone-500">{ref.deskripsi_singkat}</p><p className="mt-2 text-xs text-forest-600">Acuan: {source.roles.map(role => roles[role] || role).join(', ')}</p></div></Dialog>}
  </div>;
}
