import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Sparkles, Image, FileText, History, CheckCircle2, RefreshCw } from 'lucide-react';
import { moodboardsApi, errorMessage, newKey } from '../api/moodboards-api';
import { dateLabel, isRunning } from '../types/moodboard.types';
import type { Moodboard, Version } from '../types/moodboard.types';
import { Busy, Notice, Pill } from '../components/WorkspaceUi';
import { SourceEditor } from '../components/SourceEditor';
import { HumanSummaryView } from '../components/HumanSummaryView';
import { FindingReview } from '../components/FindingReview';
import { MarkdownExport } from '../components/MarkdownExport';
import { projectsApi } from '../../projects/api/projects-api';

type Tab = 'sources' | 'summary' | 'review' | 'markdown' | 'history';
const tabs = [{id:'sources', label:'Referensi', icon:Image}, {id:'summary', label:'Ringkasan', icon:Sparkles}, {id:'review', label:'Review temuan', icon:CheckCircle2}, {id:'markdown', label:'Markdown', icon:FileText}, {id:'history', label:'Riwayat', icon:History}] as const;
export function MoodboardWorkspacePage() {
  const { id = '', boardId = '' } = useParams();
  const [board, setBoard] = useState<Moodboard | null>(null); const [versions, setVersions] = useState<Version[]>([]); const [selected, setSelected] = useState('');
  const [tab, setTab] = useState<Tab>('sources'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [pendingUpload, setPendingUpload] = useState(false); const [dirtyReview, setDirtyReview] = useState(false); const [dirtyContext, setDirtyContext] = useState(false);
  const [aiReady, setAiReady] = useState<boolean | null>(null); const requestKey = useRef({ revision: -1, key: '' });
  const [projectArchived, setProjectArchived] = useState(false);
  const locked = projectArchived || !!board?.archived;
  const version = versions.find(v => v.id === selected) || versions[0]; const running = versions.find(isRunning);
  const refreshBoard = useCallback(async () => { setBoard(await moodboardsApi.get(id, boardId)); }, [id, boardId]);
  useEffect(() => { let active = true; const controller = new AbortController(); setLoading(true); setError('');
    Promise.all([moodboardsApi.get(id, boardId, controller.signal), moodboardsApi.versions(id, boardId, controller.signal)]).then(([b, v]) => {if (active) {setBoard(b); setVersions(v.items); setSelected(v.items[0]?.id || '');}}).catch(e => {if (active) setError(errorMessage(e));}).finally(() => {if (active) setLoading(false);});
    moodboardsApi.health().then(h => {if (active) setAiReady(h.ai_configured);}).catch(() => {});
    projectsApi.getProject(id).then(p => {if (active) setProjectArchived(p.status === 'archived');}).catch(() => {});
    return () => {active = false; controller.abort();};
  }, [id, boardId]);
  useEffect(() => {if (!running) return; const controller = new AbortController(); let active = true; let timer: ReturnType<typeof setTimeout>;
    const poll = async () => {try {const next = await moodboardsApi.version(id, boardId, running.id, controller.signal); if (!active) return; setVersions(items => items.map(v => v.id === next.id ? next : v)); if (isRunning(next)) timer = setTimeout(poll, 2500); else {await refreshBoard();}} catch (e) {if (active) {setError(errorMessage(e)); timer = setTimeout(poll, 5000);}}};
    timer = setTimeout(poll, 1500); return () => {active = false; clearTimeout(timer); controller.abort();};
  }, [running?.id, id, boardId, refreshBoard]);
  useEffect(() => {const handler = (e: BeforeUnloadEvent) => {if (dirtyReview || dirtyContext || pendingUpload) {e.preventDefault(); e.returnValue = '';}}; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler);}, [dirtyReview, dirtyContext, pendingUpload]);
  const changedVersion = useCallback((next: Version) => {setVersions(items => items.some(v => v.id === next.id) ? items.map(v => v.id === next.id ? next : v) : [next, ...items]); void refreshBoard().catch(e => setError(errorMessage(e)));}, [refreshBoard]);
  function switchTab(next: Tab) {if ((dirtyReview || dirtyContext || pendingUpload) && !window.confirm('Perubahan yang belum disimpan akan ditinggalkan. Lanjutkan?')) return; setTab(next);}
  async function analyze() {if (!board || locked) return; setBusy(true); setError(''); if (requestKey.current.revision !== board.revision) requestKey.current = {revision: board.revision, key: newKey()}; try {const next = await moodboardsApi.analyze(id, boardId, board.revision, requestKey.current.key); changedVersion(next); setSelected(next.id); setTab('summary');} catch (e) {setError(errorMessage(e));} finally {setBusy(false);}}
  async function jobAction(action: 'retry' | 'cancel') {if (!running && !version) return; setBusy(true); setError(''); try {changedVersion(await moodboardsApi.jobAction(id, boardId, (running || version).id, action));} catch(e) {setError(errorMessage(e));} finally {setBusy(false);}}
  if (loading) return <Busy/>;
  if (!board) return <div className="mx-auto max-w-6xl p-6"><Notice>{error || 'Moodboard tidak ditemukan.'}</Notice><Link className="mb-button-secondary mt-4" to={`/projects/${id}/moodboards`}>Kembali ke moodboards</Link></div>;
  return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-8"><Link className="mb-button-ghost mb-5 inline-flex pl-0 text-xs" to={`/projects/${id}/moodboards`}><ArrowLeft size={14}/>Semua moodboards</Link>
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-eyebrow mb-2">Visual direction workspace</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{board.title}</h1><p className="mt-2 text-sm text-stone-500">Dari inspirasi visual menjadi arahan yang jelas.</p></div><div className="flex flex-wrap items-center gap-3">{version && <select aria-label="Pilih versi analisis" className="mb-input w-auto" value={version.id} onChange={e => {if (dirtyReview && !window.confirm('Tinggalkan perubahan review yang belum disimpan?')) return; setSelected(e.target.value);}}>{versions.map(v => <option key={v.id} value={v.id}>Versi {v.version_number}{v.review_status === 'approved' ? ' · Disetujui' : ''}</option>)}</select>}<button className="mb-button" disabled={busy || !!running || locked || pendingUpload || dirtyContext || dirtyReview || !(board.sources || []).some(s => s.included) || aiReady === false} onClick={analyze}><Sparkles size={16}/>{busy ? 'Memproses…' : versions.length ? 'Analisis baru' : 'Analisis moodboard'}</button></div></div>
    <div className="mt-5 space-y-3"><div className="flex justify-end"><button className="mb-button-ghost text-xs" disabled={busy || !!running || projectArchived || dirtyContext || dirtyReview || pendingUpload} onClick={async () => {if (!window.confirm(board.archived ? 'Pulihkan moodboard ini?' : 'Arsipkan moodboard ini? Semua referensi dan versi tetap tersimpan.')) return; setBusy(true); try {setBoard(await moodboardsApi.update(id, boardId, {revision:board.revision, archived:!board.archived}));} catch(e) {setError(errorMessage(e));} finally {setBusy(false);}}}>{board.archived ? 'Pulihkan moodboard' : 'Arsipkan moodboard'}</button></div>{error && <Notice>{error}</Notice>}{aiReady === false && <Notice kind="info">Layanan AI belum terhubung. Anda tetap dapat mengunggah dan mengatur referensi. Pengelola workspace perlu mengaktifkan layanan analisis.</Notice>}{board.archived && <Notice kind="info">Moodboard diarsipkan. Hasil yang sudah ada tetap dapat dibaca.</Notice>}{(pendingUpload || dirtyContext) && <p className="text-xs text-stone-500">Simpan konteks dan unggah gambar yang dipilih sebelum memulai analisis.</p>}</div>
    <div className="my-6 flex gap-1 overflow-x-auto border-b border-stone-200" role="tablist" aria-label="Workspace moodboard">{tabs.map(({id: t, label, icon: Icon}) => <button key={t} role="tab" aria-selected={tab === t} className={`mb-tab whitespace-nowrap ${tab === t ? 'mb-tab-active' : ''}`} onClick={() => switchTab(t)}><Icon size={15}/>{label}</button>)}</div>
    {tab === 'sources' ? <div className="grid items-start gap-6 lg:grid-cols-[1fr_300px]"><SourceEditor projectId={id} board={board} onRefresh={refreshBoard} disabled={locked || !!running} onPending={setPendingUpload}/><ContextEditor key={board.id} board={board} onSave={setBoard} onDirty={setDirtyContext} disabled={locked || !!running}/></div> : tab === 'history' ? <div className="mb-panel divide-y divide-stone-100">{versions.length ? versions.map(v => <button key={v.id} className="flex w-full flex-wrap items-center justify-between gap-4 p-6 text-left hover:bg-stone-50" onClick={() => {setSelected(v.id); setTab('summary');}}><div><h2 className="text-sm font-semibold">Versi {v.version_number}</h2><p className="mt-1 text-xs text-stone-500">{dateLabel(v.created_at)} · {v.snapshot.sources.length} referensi · {v.snapshot.title}</p></div><Pill status={v.review_status === 'approved' ? 'approved' : v.job_status}/></button>) : <p className="p-8 text-sm text-stone-500">Riwayat muncul setelah analisis pertama.</p>}</div> : !version ? <div className="mb-panel p-12 text-center"><Sparkles size={32} className="mx-auto mb-4 text-forest-500"/><h2 className="text-lg font-semibold">Temukan benang merah visual Anda</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-stone-500">Unggah referensi dan tambahkan konteks, lalu mulai analisis untuk melihat ringkasan dan arahan visual.</p><button className="mb-button-secondary mt-5" onClick={() => setTab('sources')}>Tambahkan referensi</button></div> : <>
      {isRunning(version) && <div className="mb-panel mb-5 p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><RefreshCw size={20} className="animate-spin text-forest-600"/><h2 className="font-semibold">Analisis sedang berjalan</h2></div><button className="mb-button-secondary" disabled={busy} onClick={() => jobAction('cancel')}>Batalkan</button></div><p className="mt-3 text-sm text-stone-500">{Object.values(version.per_source).filter(s => s.status === 'succeeded').length} dari {version.snapshot.sources.length} referensi selesai. Hasil diperbarui otomatis.</p></div>}
      {['failed','partial','cancelled'].includes(version.job_status) && <div className="mb-5"><Notice kind="info">{version.job_status === 'partial' ? 'Sebagian referensi belum berhasil dianalisis. Hasil parsial belum dapat disetujui.' : version.job_status === 'cancelled' ? 'Analisis dibatalkan.' : 'Analisis gagal. Coba kembali setelah memeriksa layanan AI.'}{version.job_status !== 'cancelled' && <button className="mb-button-secondary ml-3 mt-2" disabled={busy || !!running || locked} onClick={() => jobAction('retry')}>Coba analisis kembali</button>}</Notice></div>}
      {tab === 'summary' && (version.human_summary ? <HumanSummaryView projectId={id} boardId={boardId} version={version} onReview={() => setTab('review')}/> : !isRunning(version) && <Notice kind="info">Ringkasan belum tersedia untuk versi ini.</Notice>)}
      {tab === 'review' && <FindingReview key={`${version.id}:${version.revision}`} projectId={id} boardId={boardId} version={version} onVersion={changedVersion} onDirty={setDirtyReview} readOnly={locked || !!running}/>}
      {tab === 'markdown' && <MarkdownExport key={version.id} projectId={id} boardId={boardId} version={version} onReview={() => setTab('review')}/>}
    </>}
  </div>;
}
function ContextEditor({board, onSave, onDirty, disabled}: {board: Moodboard; onSave: (b: Moodboard) => void; onDirty: (d: boolean) => void; disabled: boolean}) {
  const [title, setTitle] = useState(board.title); const [context, setContext] = useState(board.context); const [purpose, setPurpose] = useState(board.intended_use); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const dirty = title !== board.title || context !== board.context || purpose !== board.intended_use;
  useEffect(() => {onDirty(dirty); return () => onDirty(false);}, [dirty, onDirty]);
  return <form className="mb-panel space-y-5 p-6" onSubmit={async e => {e.preventDefault(); setBusy(true); setError(''); try {onSave(await moodboardsApi.update(board.project_id, board.id, {revision: board.revision, title, context, intended_use: purpose}));} catch(err) {setError(errorMessage(err));} finally {setBusy(false);}}}><div><p className="mb-eyebrow mb-2">Brief visual</p><h2 className="font-semibold">Tambahkan konteks</h2><p className="mt-2 text-xs leading-5 text-stone-500">Bantu analisis memahami tujuan dan batasan proyek Anda.</p></div><label className="mb-label">Nama moodboard<input className="mb-input mt-2" required maxLength={200} disabled={disabled || busy} value={title} onChange={e => setTitle(e.target.value)}/></label><label className="mb-label">Konteks & tujuan<textarea className="mb-input mt-2 min-h-40" maxLength={10000} disabled={disabled || busy} placeholder="Contoh: arah visual kampanye produk botanical, terasa hangat dan natural…" value={context} onChange={e => setContext(e.target.value)}/></label><label className="mb-label">Penggunaan<select className="mb-input mt-2" value={purpose} disabled={disabled || busy} onChange={e => setPurpose(e.target.value)}><option value="general">Arahan umum</option><option value="image">Generasi gambar</option><option value="video">Generasi video</option><option value="animation">Animasi</option></select></label>{error && <Notice>{error}</Notice>}<button className="mb-button-secondary w-full" disabled={!dirty || disabled || busy}>{busy ? 'Menyimpan…' : 'Simpan konteks'}</button></form>;
}
