import { useState, type ReactNode } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { Layers3, FolderOpen, Image, Clapperboard, FileText, Menu, X, HelpCircle, ArrowUpRight } from 'lucide-react';
import { Dialog } from '../../modules/moodboards/components/WorkspaceUi';

export function AppShell({children}: {children: ReactNode}) {
  const {pathname} = useLocation(); const projectId = pathname.match(/^\/projects\/([^/]+)/)?.[1]; const hasProject = projectId && projectId !== 'new';
  const [open, setOpen] = useState(false); const [help, setHelp] = useState(false);
  const links = [{to:'/projects', label:'Semua project', icon:FolderOpen, end:true}, ...(hasProject ? [{to:`/projects/${projectId}/overview`, label:'Shot management', icon:Clapperboard, end:false}, {to:`/projects/${projectId}/brief`, label:'Project brief', icon:FileText, end:false}, {to:`/projects/${projectId}/moodboards`, label:'Moodboards', icon:Image, end:false}] : [])];
  return <div className="min-h-screen bg-canvas text-ink"><aside className={`fixed inset-y-0 left-0 z-40 flex w-60 flex-col border-r border-stone-200 bg-white px-4 py-6 transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-10 flex items-center justify-between px-2"><Link to="/projects" className="flex items-center gap-3 text-lg font-semibold tracking-tight"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-forest-600 text-white"><Layers3 size={19}/></span>AI Office<span className="rounded bg-stone-100 px-1.5 py-0.5 text-[9px] text-stone-500">BETA</span></Link><button className="lg:hidden" aria-label="Tutup navigasi" onClick={() => setOpen(false)}><X size={18}/></button></div><p className="mb-eyebrow px-3">Workspace</p><nav className="mt-3 space-y-1" aria-label="Navigasi utama">{links.map(({to,label,icon:Icon,end}) => <NavLink key={to} to={to} end={end} onClick={() => setOpen(false)} className={({isActive}) => `flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-medium ${isActive ? 'bg-forest-50 text-forest-700' : 'text-stone-500 hover:bg-stone-50 hover:text-ink'}`}><Icon size={18}/>{label}</NavLink>)}</nav><div className="mt-auto rounded-xl border border-stone-100 bg-stone-50 p-4"><p className="text-sm font-medium">Mulai dengan inspirasi.</p><p className="mt-2 text-xs leading-5 text-stone-500">Susun referensi, pahami arahnya, dan bawa ide ke proses produksi.</p><button className="mt-4 flex items-center gap-2 text-xs font-semibold text-forest-700" onClick={() => setHelp(true)}>Panduan workspace<ArrowUpRight size={14}/></button></div><p className="mt-5 px-2 text-[10px] text-stone-400">Creative production, connected.</p></aside>{open && <button className="fixed inset-0 z-30 bg-ink/30 lg:hidden" aria-label="Tutup menu" onClick={() => setOpen(false)}/>}
    <div className="lg:pl-60"><header className="flex h-16 items-center justify-between border-b border-stone-200 bg-white/80 px-5 sm:px-8"><div className="flex items-center gap-4"><button className="lg:hidden" aria-label="Buka navigasi" onClick={() => setOpen(true)}><Menu size={21}/></button><span className="text-xs text-stone-500">Workspace<span className="mx-3 text-stone-300">/</span><span className="font-medium text-ink">{pathname.includes('moodboards') ? 'Moodboards' : pathname.includes('brief') ? 'Project brief' : 'Projects'}</span></span></div><button className="mb-button-ghost text-xs" onClick={() => setHelp(true)}><HelpCircle size={16}/><span className="hidden sm:inline">Panduan</span></button></header><main>{children}</main></div>
    {help && <Dialog title="Dari referensi ke arahan visual" onClose={() => setHelp(false)}><ol className="space-y-5 text-sm leading-6 text-stone-600"><li><strong className="text-ink">1. Siapkan referensi.</strong> Pilih project, buka Moodboards, lalu unggah gambar JPEG, PNG, atau WebP. Tambahkan konteks dan peran setiap gambar.</li><li><strong className="text-ink">2. Analisis dan review.</strong> Baca ringkasan, terima atau koreksi temuan, dan selesaikan konflik sebelum menyetujui versi.</li><li><strong className="text-ink">3. Gunakan Markdown.</strong> Ekspor versi yang disetujui untuk AI lain. Periksa terjemahan jika memilih bahasa Inggris.</li></ol></Dialog>}
  </div>;
}
